INSERT INTO `categories` (`id`, `name`) VALUES
    (1, 'books'),
    (2, 'technique'),
    (3, 'sportswear'),
    (4, 'kids'),
    (5, 'houses'),
    (6, 'tourism');

INSERT INTO `products` (`id`, `name`, `price`, `description`, `full_description`, `image`, `novelty`, `category_id`) VALUES
    (1, 'Alibaba. История мирового восхождения от первого лица', 32, 'Джек Ма - Рокфеллер XXI века, акции Alibaba в 2014 году побили рекорды, достигнув 25 млрд долларов.', 'Инсайдерское откровение о том, как один человек построил мировую корпорацию, способную противостоять таким гигантам как Walmart и Amazon.\r\n\r\nВсего за десять лет Джек Ма, бывший перподаватель английского, основал и построил Alibaba Group, в которую сегодня входят: Alibaba.com, Alibaba Pictures, AliExpress.com , Taobao.com, Tmall.com, Alipay и другие.\r\n\r\nДжек Ма - Рокфеллер XXI века, акции Alibaba в 2014 году побили рекорды, достигнув 25 млрд долларов.\r\n\r\nПеред вами история компании и самого Джека, иконы частного предпринимательства и привратника миллионов потребителей от китайского Ханчжоу до тверского Торжка.', '32973205.cover_330.jpg', b'1', 1),
    (2, 'Теория каст и ролей', 29, 'Революционная книга, в которой автор делит общество на касты и описывает роли людей в них.', 'Революционная книга, в которой автор делит общество на касты и описывает роли людей в них.\r\n\r\nКасты определяют уровень свободы и безопасности каждого человека.\r\n\r\nРабы, чиновники, жандармы, профессионалы, рантье, топ-менеджеры, олигархи, бизнесмены, властители, жрецы - вы сможете изучить их характеристики и определить свою касту и роль в ней как некую точку отсчета. От нее автор предложит вам путь к высшим кастам, где царит полная свобода и подлинное счастье.\r\n\r\nЭта книга способна изменить жизнь каждого, кто ее прочтет.\r\n\r\nЕще до официальной публикации она имела тысячи приверженцев.', 'BC4_1513863448.jpg', b'1', 1),
    (3, 'Стив Джобс. Биография', 30, 'Нет никаких причин не следовать велению своего сердца', '\"Мне никогда не попадалось более действенного инструмента, помогающего делать выбор в важные моменты жизни, чем сознание, что я скоро умру. Потому что почти всё – ожидания окружающих, гордость, боязнь попасть в неловкое положение или потерпеть неудачу – все эти вещи просто отступают перед лицом смерти, и остается только то, что действительно важно. Память смертная – лучший из всех известных мне способов избежать западни, в которую вас загоняет мысль о том, что вам есть, что терять. Ты уже голый. Нет никаких причин не следовать велению своего сердца.\" \r\n\r\nСейчас, когда страны всего мира пытаются выстроить новые экономики эпохи цифровых технологий, Стив Джобс является олицетворением творчества, воображения, изобретательности. ', '9781451648539.jpg', b'0', 1),
    (4, 'Время - деньги', 25, '\"Кто весь день работает, тому некогда зарабатывать деньги\" - знакомая ситуация?', '\"Кто весь день работает, тому некогда зарабатывать деньги\" - знакомая ситуация? А ведь так считал один из самых успешных и богатых предпринимателей в истории.\r\n\r\nЕсли вы хотите, но не знаете, как заработать свой первый капитал, - автобиографии Генри Форда и Джона Дэвисона Рокфеллера помогут успешно начать бизнес.\r\n\r\nСоветы, которые находятся в этой книге, можно использовать и в повседневной жизни.\r\n\r\nНапример, у Рокфеллера предпринимательская жилка появилась еще в детстве. Джон покупал фунт конфет, делил его на маленькие кучки и с наценкой распродавал собственным сестрам.\r\n\r\nМудрость и опыт этих людей послужат вам отправной точкой для финансовой независимости, помогут развить творческое мышление и успешное решение', '1018105727.jpg', b'0', 1),
    (5, 'Asus X751LB (X751LB-TY139T)', 2000, 'Тип	ноутбук\r\nДата выхода на рынок	2014 год\r\nЧастота процессора	2200 МГц', 'Тип	ноутбук\r\nДата выхода на рынок	2014 год\r\nЧастота процессора	2200 МГц\r\nНазначение	универсальный\r\nДизайн	минималистичный\r\nОсобенности конструкции	отсутствуют\r\nКласс	потребительский\r\nРазмер экрана	17.3 \"\r\nРазрешение экрана	1366x768\r\nBluetooth	4.0\r\nДлина	272 мм\r\nТолщина	36 мм\r\nШирина	415 мм', '643197_2627170.png', b'1', 2),
    (6, 'Acer Aspire ES1-732-P1YE (NX.GH4EU.009) NX.GH4EU.009', 1500, 'Тип	ноутбук\r\nДата выхода на рынок	2014 год\r\nЧастота процессора	1100 МГц', 'Тип	ноутбук\r\nДата выхода на рынок	2014 год\r\nЧастота процессора	1100 МГц\r\nНазначение	универсальный\r\nРазмер экрана	17.3 \"\r\nРазрешение экрана	1600x900\r\nBluetooth	4.0\r\nДлина	289.9 мм\r\nТолщина	27.3 мм\r\nШирина	423.3 мм', 'Laptop_PNG5940.png', b'0', 2),
    (7, 'Nike Run Revolution 4', 20, 'Upper - Textile, Lining and Sock - Textile, Sole - Other Materials.', 'Minimal in design, the men\'s Nike Revolution 4 (EU) Running Shoe is made of lightweight, single-layer mesh for breathability and soft foam beneath the foot for revolutionary comfort and responsiveness. Mesh upper for optimal breathability. Soft foam midsole delivers lightweight, responsive cushioning. Rubber outsole offers durable traction. Deep flex grooves promote natural range of motion. Rubber outsole provides traction, durability and cushioning.', '103-908s.jpg', b'1', 3),
    (8, 'adidas Originals Trefoil Overhead Hoody', 42, 'The sweatshirt is made of a heavyweight French terry with ribbed cuffs and hem', 'The classic Trefoil never goes out of style. This men\'s hoody keeps the look timeless with a rubber-print Trefoil logo on the chest. The sweatshirt is made of a heavyweight French terry with ribbed cuffs and hem.\r\n100% Cotton.', '176-862s.jpg', b'1', 3),
    (9, 'Nike Huarache Ultra', 15, 'Upper - Textile, Lining and Sock - Textile, Sole - Other Materials.', 'The Nike Air Huarache Run Men\'s Shoe brings back the iconic Huarache fit with a featherweight feel. It blends perforated foam with mesh for enhanced breathability, and features cut-outs in the outsole for light-as-air comfort. Three-layer mesh and perforated foam upper enhances ventilation. No-sew overlays on the toe and quarter for a sleek look. Elastic strap and rubber cage on the heel for a classic Huarache look. Bootie construction offers a snug, flexible fit. Pull tab on the ankle and tongue provides easy on and off. Foam midsole provides comfort and durability. Cut-outs in the sockliner, midsole and outsole deliver 360 degrees of breathability. Encapsulated Air-Sole unit for cushioning.', '193-389s.jpg', b'0', 3),
    (10, 'Nike Club Jogger', 30, '80% Cotton, 20% Polyester.', 'Mens Nike Sportswear Pant sets you up with plush comfort without the bulk. Crafted with soft fleece fabric, they feature an updated, slim waistband and cuffs for a clean look. Fleece fabric is brushed on the back for softness. Elastic waistband with drawcord for an adjustable fit. Standard fit has loose, straight legs. Side and back pockets offer small-item storage. Elastic cuffs show off your sneakers.', '454-532s2.jpg', b'0', 3),
    (11, 'Navy Mesh Trainers', 18, 'Upper - Textile, Other Materials, Lining & Sock - Textile, Sole - Other Materials.', 'Upper - Textile, Other Materials, Lining & Sock - Textile, Sole - Other Materials. Upper - Textile, Other Materials, Lining & Sock - Textile, Sole - Other Materials. Upper - Textile, Other Materials, Lining & Sock - Textile, Sole - Other Materials.', '152-802s.jpg', b'0', 3),
    (12, 'Superman Boys\' Plain Regular Fit T-Shirt', 25, 'Colour: Red Tex', 'Colour: Red Tex\r\n60% Cotton and 40% polyester\r\nHalf sleeve\r\nDo not iron on print, hand wash', '81Xpjt3jNaL._UL1500_.jpg', b'1', 4),
    (13, 'Marvel Boys\' T-Shirt\r\n', 22, '100% Cotton, Round neck, Half sleeve', '100% Cotton\r\nRound neck\r\nHalf sleeve\r\nCasual wear\r\nWash regular machine wash, may not be tumble dried, iron on medium heat setting, do not dry clean, wash similar colors together, iron on reverse side, dry immediately after washing\r\nMade in India\r\n', 'A1kMFgS5gBL._UX522_.jpg', b'0', 4),
    (14, 'Fort Collins Boys\' Regular Fit Jacket', 35, '100% Nylon, Easy hand wash', '80% Cotton and 20% polyester\r\nRound neck\r\nLong sleeve\r\nEasy hand wash', '91jcacSDJKL._UL1500_.jpg', b'0', 4),
    (15, 'Status Quo Cubs Boys\' T-Shirt', 45, '100% Cotton, Half sleeve. Half sleeve', '100% Cotton\r\nHalf sleeve\r\nMachine wash warm, wash inside out, with like colours, do not bleach, dry in shade, do not iron on prints', 'A1RUV9RbZZL._UL1500_.jpg', b'1', 4),
    (16, 'Cherokee Boys\' Trousers', 40, '100% Cotton, 100% Cotton, 100% Cotton', '100% Cotton\r\nSlim fit\r\nNormal wash', '81mOCs+o9VL._UL1500_.jpg', b'1', 4),
    (17, 'Кровать TORRECILLA 1,8м', 800, 'Цветовое исполнение: колониальный тёмно-коричневый', 'Цветовое исполнение: колониальный тёмно-коричневый\r\nМатериал: массив тополя, шпон ореха \r\nДизайн: Джоэл Кальдерон, Калифорния\r\nПроизводитель: Berkenwood Home, Вьетнам', '208095d3ffb659000824908db52c92d6.jpg', b'1', 5),
    (18, 'Кровать Ника-4', 450, 'с подъемным механизмом\r\nбез подъемного механизма', 'Кровати «Барро» в сочетании с ортопедическими матрасами «Барро», являются идеальным вариантом для всех, кто ценит изысканный стиль в интерьере и заботится о своем здоровье.\r\nПри их изготовлении , используется качественные современные материалы.', '84fa1041cb3ce9fbade2ab3227302aa7.jpg', b'0', 5),
    (19, 'Компьютерный стол МК-22 Партнер', 650, 'Материал: ДСП 16 мм\r\nЦветовая гамма: венге/дуб молочный', 'Модель МК-22 - прямой функциональный стол. МК-22 «Партнер» – это полноценное рабочее место с вместительным шкафом-пеналом и тумбой с тремя выдвижными ящиками. Надстройка над рабочим местом позволяет разместить полезные мелочи.\r\nВыпускается в левом и правом исполнении.', 'ed35b4326bd7692e62541736fa5acaad.jpg', b'0', 5),
    (20, 'Шкаф 3-дверный GRACEMONT', 750, 'Линия GRACEMONT мягко отсылает нас в стилистику прошлых десятилетий.', 'Линия GRACEMONT мягко отсылает нас в стилистику прошлых десятилетий. Времена,к которым принято прибавлять приставку «ретро-». Ретро-интерьеры, ретро-мебель....Приятная графичность изогнутых «песчаных» фасадов выгодно подчёркивается насыщенным «красным деревом» — цветом берёзового шпона, покрывающего скрытый в каркасах массив тополя.Трогательный ретро-акцент — никелированная фурнитура, тактично усиливающая геометрию композиции. Все выдвижные ящики комодов и прикроватных тумб выполнены из дерева, их внутренние поверхности обиты бархатом, а высокое резное изголовье — приятной на ощупь мягкой текстурной тканью. Коллекция Gracemont не только комфортна, но и утилитарна — она прекрасно впишется в любой традиционный интерьер! Стол туалетный GRACEMONT без зеркала имеет насыщенный цвет орех. Материл из которого он изготовлен очень прочный.', 'b27e019d2fcf2173e3d595b33416f439.jpg', b'1', 5),
    (21, 'Стул EKATERINA II FF888 орех', 250, 'Стул обеденный Ekaterina II тканевая мягкая обивка', 'Стул обеденный Ekaterina II тканевая мягкая обивка. Материал: МДФ, патинирование «золото» Цвет орех. Роспись по каркасу в французском стиле. Декор под резьбу.', 'e3b23b018365ce1ed0da784231f5ed1d.jpg', b'1', 5),
    (22, 'ПАЛАТКА SOL ANCHOR 3, SLT-031', 500, 'Трехместная палатка SOL Anchor 3 с двумя входами и тамбуром рассчитана на три взрослых человека.', 'Трехместная палатка SOL Anchor 3 с двумя входами и тамбуром рассчитана на три взрослых человека. Если вы предпочитаете отдых на природе, бескрайние леса, поляны, стремительные реки, водоемы, любите активный отдых с семьей, то в вашем арсенале принадлежностей без палатки не обойтись. Где здоровый сон, комфортные условия и защиту от насекомых обеспечено. Данная палатка с предбанником относится к кемпинговым. Тент изделия обладает влагоустойчивостью, каждый шовчик надежно проклеен и вам не страшны ни ливни, ни жара. Платка SOL Anchor 3 идеально подойдет для длительных походов в любое время и любую погоду.', 'slt_031.png', b'1', 6),
    (23, 'РЮКЗАК LIGHT 60 TRAMP, TRP-003.10', 300, 'Рюкзак Light 60 Tramp, TRP-003.10 – это практичный, большой рюкзак для путешествий.', 'Рюкзак Light 60 Tramp, TRP-003.10 – это практичный, большой рюкзак для путешествий. Выполнен из качественных материалов, прослужит вам не один десяток лет. Улучшенная модель с регулируемой подвесной и вентиляционной системами, обеспечивает равномерное распределение нагрузки и позволяет длительную носку без вреда для здоровья. Подходит для ходьбы и длительных путешествий. Функциональная и вместительная вещь имеет множество удобных элементов в своем арсенале - съемный клапан с вместительным карманом, лямки анатомической формы, много карманов и накидка от дождя. Купите наше изделие, порадуйте себя и близких приятным приобретением.', 'trp_003.10.png', b'1', 6),
    (24, 'НОЖ СКЛАДНОЙ ENLAN EW033', 150, 'Туристический складной нож Enlan EW033 - верный спутник любого путешественника.', 'Туристический складной нож Enlan EW033 - верный спутник любого путешественника. Надежную фиксацию клинка обеспечивает замок типа Liner lock , вы можете быть уверены в том, что лезвие не раскроется в самый неподходящий момент. Эргономичная рукоять является термоустойчивой и не скользящей, вы можете использовать инструмент даже влажными руками. Пользоваться клинком невероятно удобно, его режущие свойства имеют высокое качество и отличную заточку. Туристический раскладной нож не является холодным оружием. Его лезвие обладает высокой твердостью, выполнено из закаленной нержавеющей стали. Инструмент будет служить вам долгий период времени верой и правдой.', '330_551f929f90832.jpg', b'1', 6),
    (25, 'СУМКА ДОРОЖНАЯ ДЛЯ АВТОМОБИЛЯ 1027', 100, 'Сумка дорожная для автомобиля – отличный помощник автомобилиста.', 'Сумка дорожная для автомобиля – отличный помощник автомобилиста. Она решает проблему транспортировки всевозможных инструментов, запчастей и прочих необходимых вещей в дороге. Во время движения все надежно зафиксировано, не болтается и не издает шум. В раскрытом виде органайзер в багажник автомобиля принимает удобную форму коробки. Практичные характеристики дополнены отличным дизайном. Купить складной ящик-органайзер для своей машины можете в интернет магазине Экспедиция. И Вам больше не придется бесконечно наводить порядок в багажнике, собирать разбросанные вещи и устранять следы протекших жидкостей!', '9b76ecca7c.jpg', b'0', 6),
    (26, 'ТЕРМОС HAERS 1600 МЛ,СИНИЙ,HG-1600-2', 50, 'Крышка имеет сплошное основание с ручкой, поэтому отсутствует риск ее потерять.', 'Объемный термос из нержавеющей стали с удобной ручкой может использоваться для хранения горячих и холодных напитков. Крышка имеет сплошное основание с ручкой, поэтому отсутствует риск ее потерять. Термос оснащен пробкой с кнопкой и узким дозатором, что позволяет наливать жидкость в полузакрытом виде. Термос удобно брать с собой на пикник либо в поход.', 'hg_1600_2-_-1.jpg', b'0', 6);

INSERT INTO `users` (`id`, `name`, `email`, `username`, `password`) VALUES
    (1, 'MannayaKasha', 'secret@gmail.com', 'MannayaKasha', 'mannaya_kasha_root_password'),
    (2, 'TagShai', 'test@gmail.com', 'TagShai', 'test_password');

INSERT INTO `roles` (`id`, `name`) VALUES
    (1, 'ADMIN'),
    (2, 'USER');

INSERT INTO `user_roles` (`user_id`, `role_id`) VALUES
    (1, 1),
    (2, 2);

INSERT INTO `wishes` (`id`, `user_id`, `product_id`) VALUES
    (1, 2, 15);

--INSERT INTO `orders` (`id`, `user_id`, `status_id`, `total`) VALUES
    --(1, 1, 2, );

--INSERT INTO `order_items` (`id`, `product_id`, `order_id`, `quantity`, `price`) VALUES
    --(1, 5, 1, 1, )

--INSERT INTO `shipments_information` (`id`, `order_id`, `country`, `phone_number`, `address_line_1`, `address_line_2`, `zip`, `shipment_tracking_number`, `shipment_placed_date`) VALUES
	--(1, 1, 'Japan', '+954 (41) 123-45-67', 'Kyoto, Higashiyama District, Yasaka Shrine', '', '123456', 'ACF1546FD4634KM' SYSDATE());

INSERT INTO `order_statuses` (`id`, `name`) VALUES
    (1, 'NEW'),
    (2, 'SHIPPED'),
    (3, 'DELIVERED'),
    (4, 'CLOSED');